In [95]:
import numpy as np

A = np.array([[3,6],[2,3],[0,0],[0,0]])
A

array([[3, 6],
       [2, 3],
       [0, 0],
       [0, 0]])

In [138]:
U = np.dot(A , A.T)
U

array([[45, 24,  0,  0],
       [24, 13,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [139]:
V = np.dot(A.T , A)
V

array([[13, 24],
       [24, 45]])

In [140]:
U_eigen ,U_vector= np.linalg.eig(U)
print(U_eigen)
U_vector

[57.8444102  0.1555898  0.         0.       ]


array([[ 0.8816746 , -0.47185793,  0.        ,  0.        ],
       [ 0.47185793,  0.8816746 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [141]:
V_eigen ,V_vector = np.linalg.eig(V.T)
print(V_eigen)
print(V_vector)

[ 0.1555898 57.8444102]
[[-0.8816746  -0.47185793]
 [ 0.47185793 -0.8816746 ]]


In [142]:
u, s, vh = np.linalg.svd(A)

In [143]:
A

array([[3, 6],
       [2, 3],
       [0, 0],
       [0, 0]])

In [144]:
u

array([[-0.8816746 , -0.47185793,  0.        ,  0.        ],
       [-0.47185793,  0.8816746 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [145]:
s

array([7.60555128, 0.39444872])

In [150]:
S = np.diag(s,(2,4))
S

TypeError: bad operand type for abs(): 'tuple'

In [147]:
vh

array([[-0.47185793, -0.8816746 ],
       [ 0.8816746 , -0.47185793]])

In [149]:
np.dot(np.dot(u, S), vh)

ValueError: shapes (4,4) and (2,2) not aligned: 4 (dim 1) != 2 (dim 0)

In [130]:
U_vector.dot(S).dot(V_vector)

array([[-6., -3.],
       [-3., -2.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [151]:
from numpy.linalg import svd

A = np.array([[3, -1], [1, 3], [1, 1]])
U, S, VT = svd(A)

In [152]:
U

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -2.06937879e-16,  9.12870929e-01]])

In [153]:
S

array([3.46410162, 3.16227766])

In [154]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [155]:
np.diag(S, 1)[:, 1:]

array([[3.46410162, 0.        ],
       [0.        , 3.16227766],
       [0.        , 0.        ]])

In [156]:
U @ np.diag(S, 1)[:, 1:] @ VT

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

In [157]:
U2, S2, VT2 = svd(A, full_matrices=False)

In [158]:
U2

array([[-4.08248290e-01,  8.94427191e-01],
       [-8.16496581e-01, -4.47213595e-01],
       [-4.08248290e-01, -2.06937879e-16]])

In [159]:
S2

array([3.46410162, 3.16227766])

In [160]:
VT2

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [161]:
np.diag(S2) 

array([[3.46410162, 0.        ],
       [0.        , 3.16227766]])

In [162]:
U2 @ np.diag(S2) @ VT2

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])